fullnameOverride: oracle

replicaCount: 4

statefulset: true

image:
  tag: v1.5.2

env:
  ENV: prod
  NETWORK: mainnet
  GSM_PROJECT: leequid-secret
  BUCKET_NAME: leequid-prod-staking
  BUCKET_DEPOSIT_DATA_PATH: mainnet/leequid-deposit-pubkeys.json
  ARCHIVE_NODE_HOSTS: leequid-0.leequid,leequid-1.leequid,leequid-2.leequid,leequid-3.leequid
  IPFS_GATEWAY_HOSTS: ipfs.io,red-hushed-lynx-866.mypinata.cloud,leequid.infura-ipfs.io
  POSTGRES_USER: ops
  POSTGRES_HOST: postgresql
  CONTRACT_ORACLES: 0x987E6dA8F94D56D5742958f99950860FA5B120cC
  CONTRACT_DEPOSIT: 0xCAfe00000000000000000000000000000000CAfe
  CONTRACT_POOL: 0x7B6D1201A9e98B16EFef58CC42afFeb8D805d120
  CONTRACT_POOL_VALIDATORS: 0x8a53E2cdDC2242E79E98Eeffb531582d2FBb7476
  CONTRACT_SLYX: 0xDF9124ee97d7a8eB8fe845b6C6eE8a8D75B55a57
  CONTRACT_REWARDS: 0x5D48F7FC221ABcAC5386c374eF723a56AD03D4B4
  CONTRACT_MERKLE_DISTRIBUTOR: 0x555D2044145280397Ef298205048d3a3eA784abc
  LIQUIDITY_POOLS: 0xb9ddae8a609167472549f7a68425c47dba3515ec
  ORACLE_PRIVATE_KEY: /var/run/secrets/ORACLE_PRIVATE_KEY
  PROTOCOL_START_BLOCK: "953558"
  LEEQUID_OPERATOR_ADDRESS: 0x6d975e3f0c15db1bbf987da6ac244abb9faa6163
  NODE_OPERATOR_FEE: "50"
  NODE_OPTIONS: --max-old-space-size=4096
  DEBUG: true

secrets:
  PINATA_API_KEY: leequid
  INFURA_IPFS_API_KEY: leequid
  INFURA_IPFS_KEY_SECRET: leequid
  POSTGRES_PASSWORD: postgresql/password

init:
  enabled: true

postgresql:
  enabled: true

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 1Gi
