{
 "title": "LEEQUID monitoring testnet",
 "time": { "from": "2023-09-12T04:35:10.533Z", "to": "2023-09-28T04:35:10.533Z" },
 "templating": {
  "list": [
   {
    "name": "rewards",
    "label": "Rewards contract",
    "query": "0xAED7cD8d3105F4d6B4dDF99f619dCB2a26D0a900"
   },
   {
    "name": "slyx",
    "label": "StakedLyxToken contract",
    "query": "0x66712679875B99Cc73f567Fe63C564299D09812B"
   },
   {
    "name": "pool",
    "label": "Pool contract",
    "query": "0xC0bEee1133e332039dE494E51B02a7Cf8bDf37A9"
   },
   {
    "name": "pool_validators",
    "label": "Pool Validators contract",
    "query": "0x3157e5af102955Fb01349E19DF38C9c7dCBdd3C4"
   },
   {
    "name": "merkle_distributor",
    "label": "MerkleDistributor contract",
    "query": "0x66899DE87d70BDd02Fd87CD8090bD8827A8ACe31"
   },
   {
    "name": "oracles",
    "label": "Oracles contract",
    "query": "0x3fbda838D30354c9eCed17b1568f11Bba7dc7F20"
   },
   {
    "name": "univ2",
    "label": "Swap v1 contract",
    "query": "0x4ce5a2c718d91aefb4674033bce34415dd390182"
   },
   {
    "name": "deposit",
    "label": "Deposit contract",
    "query": "0xCAfe00000000000000000000000000000000CAfe"
   }
  ]
 },
 "panels": [
  {
   "title": "Effective validators",
   "type": "stat",
   "description": "Total amount of validators that are currently validating the network for the protocol",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ActivatedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'activatedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    },
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ExitedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'exitedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    }
   ]
  },
  {
   "title": "Unstaked validators",
   "type": "stat",
   "description": "Total amount of validators that were volontarely exited",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ExitedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'exitedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    }
   ]
  },
  {
   "title": "Pending activation",
   "type": "stat",
   "description": "Amount of validators being pending activation",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*)\r\nFROM \r\n  event as e\r\nJOIN \r\n  event_parameter as ep \r\nON \r\n  e.id = ep.\"eventId\"\r\nWHERE \r\n  e.address = '${deposit:raw}' \r\n  AND e.\"eventName\" = 'DepositEvent'\r\n  AND ep.name = 'withdrawal_credentials'\r\n  AND ep.value = '0x010000000000000000000000aed7cd8d3105f4d6b4ddf99f619dcb2a26d0a900';\r\n"
    },
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ActivatedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'activatedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    }
   ]
  },
  {
   "title": "Stakers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(DISTINCT to_value) AS distinct_to_value_count\r\nFROM (\r\n    SELECT \r\n        MAX(CASE WHEN ep.name = 'to' THEN ep.value END) AS to_value\r\n    FROM event e \r\n    JOIN event_parameter ep ON e.id = ep.\"eventId\"\r\n    WHERE e.address = '${slyx:raw}' \r\n        AND e.\"eventName\" = 'Transfer'\r\n        AND e.id IN (\r\n            SELECT \"eventId\" \r\n            FROM event_parameter \r\n            WHERE name = 'from' \r\n            AND value = '0x0000000000000000000000000000000000000000'\r\n        )\r\n    GROUP BY  e.id, e.\"blockNumber\", e.date, e.\"transactionHash\"\r\n) AS subquery;\r\n"
    }
   ]
  },
  {
   "title": "sLYX supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sLYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.sLYXSupply", "name": "balance" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Dillution",
   "type": "stat",
   "description": "Total amount of activated stake",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ActivatedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'activatedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    },
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ExitedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'exitedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.sLYXSupply" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Staked",
   "type": "stat",
   "description": "Total amount of activated stake",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "targets": [
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ActivatedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'activatedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    },
    {
     "rawSql": "WITH result AS (\r\n  SELECT event_parameter.value \r\n  FROM event \r\n  INNER JOIN event_parameter ON event_parameter.\"eventId\" = event.id \r\n  WHERE \"eventName\" = 'ExitedValidatorsUpdated'\r\n        AND event.address = '${pool:raw}'\r\n        AND event_parameter.name = 'exitedValidators'\r\n  ORDER BY event.\"blockNumber\" DESC\r\n  LIMIT 1\r\n)\r\n\r\nSELECT COALESCE(\r\n  (SELECT value FROM result),\r\n  '0'\r\n) AS value;\r\n"
    }
   ]
  },
  {
   "title": "Total rewards",
   "type": "stat",
   "description": "Total amount of LYX pending to be unstaked from the protocol",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "targets": [
    {
     "rawSql": "SELECT event_parameter.value FROM event INNER JOIN event_parameter \r\nON event_parameter.\"eventId\"=event.id \r\nWHERE \"eventName\"='RewardsUpdated'\r\n       AND event.address='${rewards:raw}'\r\n        AND event_parameter.name='totalRewards'\r\nORDER BY event.\"blockNumber\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Pending unstake",
   "type": "stat",
   "description": "Total amount of LYX pending to be unstaked from the protocol",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "targets": [
    {
     "rawSql": "SELECT event_parameter.value FROM event INNER JOIN event_parameter \r\nON event_parameter.\"eventId\"=event.id \r\nWHERE (\"eventName\"='UnstakeProcessed' OR \"eventName\"='UnstakeMatched' \r\n       OR \"eventName\"='NewUnstakeRequest') \r\n       AND event.address='${slyx:raw}'\r\n        AND event_parameter.name='newTotalPendingUnstake'\r\nORDER BY event.\"blockNumber\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Orchestrator Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.orchestratorKeyBalance", "name": "balance" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Latest validators registered",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    e.\"blockNumber\",\r\n    e.date,\r\n    e.\"transactionHash\",\r\n    MAX(CASE WHEN ep.name = 'pubkey' THEN ep.value END) AS pubkey_value\r\nFROM event e \r\nJOIN event_parameter ep ON e.id = ep.\"eventId\"\r\nWHERE e.address = '${deposit:raw}' \r\n    AND e.\"eventName\" = 'DepositEvent'\r\n    AND e.id IN (\r\n        SELECT \"eventId\" \r\n        FROM event_parameter \r\n        WHERE name = 'withdrawal_credentials' \r\n        AND value = '0x010000000000000000000000aed7cd8d3105f4d6b4ddf99f619dcb2a26d0a900'\r\n    )\r\nGROUP BY  e.id, e.\"blockNumber\", e.date, e.\"transactionHash\"\r\nORDER BY e.\"blockNumber\" DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "Validators registered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  Date(e.date) as event_date,\r\n  COUNT(*) as \"Number of validators\"\r\nFROM \r\n  event as e\r\nJOIN \r\n  event_parameter as ep \r\nON \r\n  e.id = ep.\"eventId\"\r\nWHERE \r\n  e.address = '${deposit:raw}' \r\n  AND e.\"eventName\" = 'DepositEvent'\r\n  AND ep.name = 'withdrawal_credentials'\r\n  AND ep.value = '0x010000000000000000000000e7f1725e7734ce288f8367e1bb143e90bb3f0512'\r\nGROUP BY \r\n  event_date\r\nORDER BY \r\n  event_date;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    e.date,\r\n    MAX(CASE WHEN ep.name = 'validatorsToExit' THEN ep.value END) AS \"Validators to exit\"\r\nFROM event e \r\nJOIN event_parameter ep ON e.id = ep.\"eventId\"\r\nWHERE e.address = '${slyx:raw}' \r\n    AND e.\"eventName\" = 'UnstakeReady'\r\nGROUP BY  e.id, e.\"blockNumber\", e.date, e.\"transactionHash\"\r\nORDER BY e.\"blockNumber\" DESC\r\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Evolution of registered validators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  DATE(e.date) as event_date,\r\n  SUM(COUNT(*)) OVER (ORDER BY DATE(e.date)) as \"Number of validators\"\r\nFROM \r\n  event as e\r\nJOIN \r\n  event_parameter as ep \r\nON \r\n  e.id = ep.\"eventId\"\r\nWHERE \r\n  e.address = '${deposit:raw}' \r\n  AND e.\"eventName\" = 'DepositEvent'\r\n  AND ep.name = 'withdrawal_credentials'\r\n  AND ep.value = '0x010000000000000000000000aed7cd8d3105f4d6b4ddf99f619dcb2a26d0a900'\r\nGROUP BY \r\n  event_date\r\nORDER BY \r\n  event_date;\r\n"
    },
    {
     "rawSql": "SELECT \r\n  Date(e.date) as event_date,\r\n  ep.value as \"Exited validators\"\r\nFROM \r\n  event as e\r\nJOIN \r\n  event_parameter as ep \r\nON \r\n  e.id = ep.\"eventId\"\r\nWHERE \r\n  e.address = '${pool:raw}'\r\n  AND e.\"eventName\" = 'ExitedValidatorsUpdated'\r\n  AND ep.name = 'exitedValidators'\r\nGROUP BY \r\n  event_date, ep.value\r\nORDER BY \r\n  event_date;\r\n"
    }
   ]
  },
  {
   "title": "Latest validators registered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(e.id) AS \"Rewards Submitted\",\r\n    e.date\r\nFROM event e\r\nWHERE e.address = '${oracles:raw}' \r\n    AND e.\"eventName\" = 'RewardsVoteSubmitted'\r\n    GROUP BY e.date;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(e.id) AS \"Merkle Submitted\",\r\n    e.date\r\nFROM event e\r\nWHERE e.address = '${oracles:raw}' \r\n    AND e.\"eventName\" = 'MerkleRootVoteSubmitted'\r\n    GROUP BY e.date;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(e.id) AS \"Validators registered\",\r\n    e.date\r\nFROM event e\r\nWHERE e.address = '${oracles:raw}' \r\n    AND e.\"eventName\" = 'RegisterValidatorsVoteSubmitted'\r\n    GROUP BY e.date;\r\n"
    },
    {
     "rawSql": "SELECT \r\n    COUNT(e.id) AS \"Unstake processing\",\r\n    e.date\r\nFROM event e\r\nWHERE e.address = '${oracles:raw}' \r\n    AND e.\"eventName\" = 'UnstakeProcessingVoteSubmitted'\r\n    GROUP BY e.date;\r\n"
    }
   ]
  },
  {
   "title": "Latest unstake requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    e.\"blockNumber\",\r\n    e.date,\r\n    e.\"transactionHash\",\r\n    MAX(CASE WHEN ep.name = 'requestIndex' THEN ep.value END) AS index,\r\n    MAX(CASE WHEN ep.name = 'account' THEN ep.value END) AS account,\r\n    MAX(CASE WHEN ep.name = 'amount' THEN ep.value END) AS amount\r\nFROM event e \r\nJOIN event_parameter ep ON e.id = ep.\"eventId\"\r\nWHERE e.address = '${slyx:raw}' \r\n    AND e.\"eventName\" = 'NewUnstakeRequest'\r\nGROUP BY  e.id, e.\"blockNumber\", e.date, e.\"transactionHash\"\r\nORDER BY e.\"blockNumber\" DESC\r\nLIMIT 20;\r\n"
    }
   ]
  },
  {
   "title": "Need to unstake",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    e.\"blockNumber\",\r\n    e.date,\r\n    e.\"transactionHash\",\r\n    MAX(CASE WHEN ep.name = 'validatorsToExit' THEN ep.value END) AS \"Validators to exit\"\r\nFROM event e \r\nJOIN event_parameter ep ON e.id = ep.\"eventId\"\r\nWHERE e.address = '${slyx:raw}' \r\n    AND e.\"eventName\" = 'UnstakeReady'\r\nGROUP BY  e.id, e.\"blockNumber\", e.date, e.\"transactionHash\"\r\nORDER BY e.\"blockNumber\" DESC\r\nLIMIT 20;"
    }
   ]
  }
 ]
}