apiVersion: v2
name: app
description: Leequid App chart for backend apps
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: redis
    version: 17.15.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
