replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/leequid/leequid/leequid-xxx
  tag: latest
  pullPolicy: Always #Never|Always|IfNotPresent

imagePullSecrets: []

env:
  NETWORK: testnet
  ENV: dev
  BUCKET_NAME: leequid-dev-staking
  GSM_PROJECT: leequid-secret
  GENESIS: genesis

secrets:
  ETH_STATS_SECRET: leequid

init:
  image: europe-west1-docker.pkg.dev/leequid/leequid/init:geth1.13.2-prysm4.0.8

exec:
  enabled: true
  image: ethereum/client-go:v1.13.2
#  memory: 2Gi

beacon:
  enabled: true
  image: europe-west1-docker.pkg.dev/leequid/leequid/prysm:v4.0.8
#  memory: 8Gi

validator:
  enabled: true
  image: europe-west1-docker.pkg.dev/leequid/leequid/prysm:v4.0.8
#  memory: 4Gi

volume:
  name: data
  storageClassName: premium-rwo
  size: 20Gi

monitoring:
  enabled: true

configmap:
  prysm:
    suggestedFeeRecipient: 0x9658B1Ff55597303EF2Ed963A9E8Aadb7E3E135e
    bootstrapNodes:
      - enr:-MK4QJ-Bt9HATy4GQawPbDDTArtnt_phuWiVVoWKhS7-DSNjVzmGKBI9xKzpyRtpeCWd3qA9737FTdkKGDgtHfF4N-6GAYlzJCVRh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA2ulfbQgAABP__________gmlkgnY0gmlwhCKTScGJc2VjcDI1NmsxoQJNpNUERqKhA8eDDC4tovG3a59NXVOW16JDFAWXoFFTEYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
      - enr:-MK4QHcS3JeTtVjOuJyVXvO1E6XJWqiwmhLfodel6vARPI8ve_2q9vVn8LpIL964qBId7zGpSVKw6oOPAaRm2H7ywYiGAYmHDeBbh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA2ulfbQgAABP__________gmlkgnY0gmlwhCIgwNOJc2VjcDI1NmsxoQNGVC8JPcsqsZPoohLP1ujAYpBfS0dBwiz4LeoUQ-k5OohzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
    slotsPerArchivePoint: 2048
    verbosity: warn
  geth:
    networkId: 4201
    bootstrapNodes:
      - '"enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.141.196.212:30303"'
      - '"enode://4cee52dc3cdc0f9466d40354c0ae038b561eff0409f01092d44d692f35797a0f3e796481c5ad1ca9afb4ea00dcceaaddbf3a79ec311221bfad3567ba347e329b@34.91.156.224:30303"'
    verbosity: 2 # warn

externalIPs: []

serviceAccount:
  create: false
  annotations:
    iam.gke.io/gcp-service-account: leequid-dev@leequid.iam.gserviceaccount.com
  name: ""

podAnnotations: {}

labels:
  chain: lukso

podSecurityContext: {}
# fsGroup: 2000
# runAsUser: 1000
# runAsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # allowPrivilegeEscalation: false

nodeSelector: {}

tolerations: []

affinity: {}
