replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/leequid/leequid/leequid-xxx
  tag: latest
#  pullPolicy: Always #Never|Always|IfNotPresent

imagePullSecrets: []

env:
  NETWORK: testnet
  ENV: dev
  BUCKET_NAME: leequid-dev-staking
  GSM_PROJECT: leequid-secret
  GENESIS: genesis

secrets:
  ETH_STATS_SECRET: leequid

init:
  image: europe-west1-docker.pkg.dev/leequid/leequid/init:geth1.11.6-prysm4.0.7

exec:
  enabled: true
  image: ethereum/client-go:v1.11.6
#  memory: 4Gi

beacon:
  enabled: true
  image: prysmaticlabs/prysm-beacon-chain:v4.0.7
#  memory: 6Gi

validator:
  enabled: true
  image: prysmaticlabs/prysm-validator:v4.0.7
#  memory: 4Gi

volume:
  name: data
  storageClassName: premium-rwo
  size: 20Gi

configmap:
  prysm:
    suggestedFeeRecipient: 0x859aC430475116A70E022860E44847bEB4ff8159
    bootstrapNodes:
      - enr:-MK4QPAebhGrV0IdXCaVQ33cL-5oySUvBXPkXZTHhCDrqMOtITlhab5B6PL9hfQY5NuRF5ctLcSFhHMCdLT4RWxxo-SGAYiVi7DIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCvClM1QgEABP__________gmlkgnY0gmlwhCKNxNSJc2VjcDI1NmsxoQISdsDnr_lxpAXRQmeOu-F_eAtxypZI4ctFavqdagbka4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
      - enr:-MK4QMEZyb5vA6A4664OJNbdRF7QQHtSMISOqU9CF8qcdB7BBjX0HsQY92roqS-0n1wTyiuCFT0weAIE7FkukdnjL0GGAYli9q2wh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCvClM1QgEABP__________gmlkgnY0gmlwhCJbnOCJc2VjcDI1NmsxoQJvUBwASZv0klLo0Zz51eb_LCQx-lNrNPp-lLULQBTpfYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
    slotsPerArchivePoint: 2048
    verbosity: warn
  geth:
    networkId: 4201
    bootstrapNodes:
      - '"enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.141.196.212:30303"'
      - '"enode://4cee52dc3cdc0f9466d40354c0ae038b561eff0409f01092d44d692f35797a0f3e796481c5ad1ca9afb4ea00dcceaaddbf3a79ec311221bfad3567ba347e329b@34.91.156.224:30303"'
    verbosity: 2 # warn

serviceAccount:
  create: false
  annotations:
    iam.gke.io/gcp-service-account: leequid-dev@leequid.iam.gserviceaccount.com
  name: ""

podAnnotations: {}

labels:
  chain: lukso

podSecurityContext: {}
# fsGroup: 2000
# runAsUser: 1000
# runAsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # allowPrivilegeEscalation: false

nodeSelector: {}

tolerations: []

affinity: {}
