{{- if .Values.externalIPs }}
{{- range $index, $ip :=  .Values.externalIPs -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $index }}
  labels:
    {{- include "staking.labels" $ | nindent 4 }}
    protocol: tcp

spec:
  type: LoadBalancer
  loadBalancerIP: "{{ $ip }}"
  selector:
    {{- include "staking.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $index }}

  ports:
    - name: sync
      port: 30303
      protocol: TCP
    - name: libp2p
      port: 13000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $index }}-udp
  labels:
    {{- include "staking.labels" $ | nindent 4 }}
    protocol: udp
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ $ip }}"
  selector:
    {{- include "staking.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $index }}

  ports:
    - name: discovery
      port: 30303
      protocol: UDP
    - name: discv5
      port: 12000
      protocol: UDP
---
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "staking.fullname" . }}
  labels:
    {{- include "staking.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "staking.selectorLabels" . | nindent 4 }}

  ports:
    - name: exec-http
      port: 8545
      protocol: TCP
    - name: beacon-http
      port: 3500
      protocol: TCP
