apiVersion: v1
kind: Service
metadata:
  name: leequid-0
  labels:
    app.kubernetes.io/instance: leequid
    app.kubernetes.io/name: staking
    chain: lukso
spec:
  type: LoadBalancer
  loadBalancerIP: "34.79.161.30"
  selector:
    app.kubernetes.io/instance: leequid
    app.kubernetes.io/name: staking
    statefulset.kubernetes.io/pod-name: leequid-0

  ports:
    - name: exec-http
      port: 8545
      protocol: TCP
    - name: beacon-http
      port: 3500
      protocol: TCP
    - name: sync
      port: 30303
      protocol: TCP
    - name: discovery
      port: 30303
      protocol: UDP
    - name: libp2p
      port: 13000
      protocol: TCP
    - name: discv5
      port: 12000
      protocol: UDP
