apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lukso
  namespace: mainnet
  labels:
    app: lukso
  annotations: {}
spec:
  replicas: 2
  serviceName: lukso
  selector:
    matchLabels:
      app: lukso
  template:
    metadata:
      labels:
        app: lukso
    spec:
      initContainers:
        - name: network-init
          image: google/cloud-sdk:434.0.0-alpine
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              gsutil -m cp -r gs://leequid-prod-lukso/mainnet/${NODE_NAME}/keystores /data
              gsutil -m cp -r gs://leequid-prod-lukso/mainnet/network-configs /data
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data

        - name: geth-init
          image: ethereum/client-go:v1.11.6
          command: ["/bin/sh", "-c"]
          args:
            - geth --datadir=/data/execution_data init /data/network-configs/genesis_42.json
          volumeMounts:
            - name: data
              mountPath: /data

        - name: prysm-validator-init
          image: prysmaticlabs/prysm-validator:v4.0.3
          args:
            - accounts
            - import
            - --keys-dir=/data/keystores
            - --wallet-dir=/data/keystores/prysm
            - --wallet-password-file=/var/run/secrets/WALLET_SECRET
            - --account-password-file=/var/run/secrets/ACCOUNT_SECRET
            - --accept-terms-of-use
          volumeMounts:
            - name: data
              mountPath: /data
            - name: secrets
              mountPath: /var/run/secrets
              readOnly: true

      containers:
        ## EXEC:GETH
        - name: exec
          image: ethereum/client-go:v1.11.6
          command: [ "/bin/sh", "-c" ]
          args:
            - geth --config /configs/geth.toml --ethstats "dropps-$(NODE_NAME):$(ETH_STATS_SECRET)@$(ETH_STATS_ADDRESS)"
              --verbosity 2
          ports:
            - name: http
              containerPort: 8545
              protocol: TCP
            - name: ws
              containerPort: 8546
              protocol: TCP
            - name: sync
              containerPort: 30303
              protocol: TCP
            - name: discovery
              containerPort: 30303
              protocol: UDP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETH_STATS_ADDRESS
              value: "stats.execution.mainnet.lukso.network"

            # SECRETS
            - name: ETH_STATS_SECRET
              valueFrom:
                secretKeyRef:
                  name: lukso
                  key: ETH_STATS_SECRET
                  optional: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: lukso-conf
              mountPath: /configs
              readOnly: true
            - name: secrets
              mountPath: /var/run/secrets
              readOnly: true
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi

        ## CONSENSUS:PRYSM (BEACON CHAIN)
#        - name: beacon
#          image: prysmaticlabs/prysm-beacon-chain:v4.0.5
#          args:
#            - --config-file=/configs/prysm.yaml
#            - --datadir=/data/consensus_data
#            - --verbosity=warn
#          volumeMounts:
#            - name: data
#              mountPath: /data
#            - name: lukso-conf
#              mountPath: /configs
#              readOnly: true
#          resources:
#            requests:
#              memory: 6Gi
#            limits:
#              memory: 6Gi
#
#        ## VALIDATOR:PRYSM
#        - name: validator
#          image: prysmaticlabs/prysm-validator:v4.0.5
#          args:
#            - --config-file=/configs/prysm.yaml
#            - --datadir=/data/validator_data
#            - --verbosity=warn
#          volumeMounts:
#            - name: data
#              mountPath: /data
#            - name: lukso-conf
#              mountPath: /configs
#              readOnly: true
#            - name: secrets
#              mountPath: /var/run/secrets
#              readOnly: true
#          resources:
#            requests:
#              memory: 4Gi
#            limits:
#              memory: 4Gi

      volumes:
        - name: lukso-conf
          configMap:
            name: lukso-conf
        - name: secrets
          secret:
            secretName: lukso
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lukso-conf
  namespace: mainnet
data:
  geth.toml: |
    [Eth]
    NetworkId = 42
    
    [Eth.Miner]
    GasCeil = 42000000
    GasPrice = 2200000000 # 2.2 Gwei
    
    [Node]
    DataDir = "/data/execution_data"
    
    [Node.P2P]
    BootstrapNodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.73.193:30303", "enode://276f14e4049840a0f5aa5e568b772ab6639251149a52ba244647277175b83f47b135f3b3d8d846cf81a8e681684e37e9fc10ec205a9841d3ae219aa08aa9717b@34.32.192.211:30303"]
    BootstrapNodesV5 = []
    
    StaticNodes = []
    TrustedNodes = []
    
    NoDiscovery = false
    DiscAddr = ""
    EnableMsgEvents = false

  prysm.yaml: |
    chain-config-file: '/data/network-configs/config.yaml'
    genesis-state: '/data/network-configs/genesis_42.ssz'
    jwt-secret: '/data/execution_data/geth/jwtsecret'
    wallet-dir: '/data/keystores/prysm'
    wallet-password-file: '/var/run/secrets/WALLET_SECRET'
    suggested-fee-recipient: '0x859aC430475116A70E022860E44847bEB4ff8159'
    
    min-sync-peers: 0
    monitoring-host: '0.0.0.0'
    grpc-gateway-host: '0.0.0.0'
    rpc-host: '0.0.0.0'
    p2p-host-ip: '0.0.0.0'
    p2p-max-peers: 250
    subscribe-all-subnets: true
    minimum-peers-per-subnet: 0
    block-batch-limit: 512
    block-batch-limit-burst-factor: 10
    accept-terms-of-use: true
    
    bootstrap-node: ['enr:-MK4QHdcy0ljlcSOPBGd2ydCh0-Rd-rRKqExylHiKunbJC3eI3DKSh4fGNM4pDnNYNvRu-9llVB1pMXloywn4XzVWhWGAYgmkP7yh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDcUbERQgAABKQfAAAAAAAAgmlkgnY0gmlwhCKTScGJc2VjcDI1NmsxoQJNpNUERqKhA8eDDC4tovG3a59NXVOW16JDFAWXoFFTEYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A','enr:-MK4QJYK0ArJzW24bL9153Zn7Za1mIpqxppv1MjtyI3jnhtsS5pStbJMB7-DNwv2M14IsecRJ-L40-Zo1mLchw_egOeGAYgmPWCch2F0dG5ldHOIAAAAAAAAAACEZXRoMpDcUbERQgAABKQfAAAAAAAAgmlkgnY0gmlwhCIgwNOJc2VjcDI1NmsxoQNGVC8JPcsqsZPoohLP1ujAYpBfS0dBwiz4LeoUQ-k5OohzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A']
