# https://github.com/lukso-network/network-docker-containers/blob/main/docker-compose.yml
# https://geth.ethereum.org/docs/fundamentals/command-line-options
# https://github.com/ethereum/go-ethereum
# https://github.com/lukso-network/network-docker-containers/blob/main/.env.example
# https://github.com/lukso-network/network-configs/blob/main/mainnet/geth/geth.toml
# https://github.com/lukso-network/network-configs
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lukso
  labels:
    app: lukso
  annotations: {}
spec:
  replicas: 1
  serviceName: lukso
  selector:
    matchLabels:
      app: lukso
  template:
    metadata:
      labels:
        app: lukso
    spec:
      initContainers:
        - name: network-init
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              url=https://raw.githubusercontent.com/lukso-network/network-configs/main/testnet/shared
              dir=/data/network-configs
              mkdir -p $dir
              wget -O ${dir}/config.yaml ${url}/config.yaml
              wget -O ${dir}/genesis.json ${url}/genesis.json
              wget -O ${dir}/genesis.ssz ${url}/genesis.ssz
          volumeMounts:
            - name: data
              mountPath: /data

        - name: geth-init
          image: ethereum/client-go:v1.11.6 # latest: v1.12.0
          command: ["/bin/sh", "-c"]
          args:
            - geth --datadir=/data/execution_data init /data/network-configs/genesis.json
          volumeMounts:
            - name: data
              mountPath: /data

      containers:
        ## EXEC:GETH
        - name: geth
          image: ethereum/client-go:v1.11.6 # latest: v1.12.0
          command: [ "/bin/sh", "-c" ]
          args:
            - geth --config /configs/geth.toml --ethstats "$(NODE_NAME):$(ETH_STATS_SECRET)@$(ETH_STATS_ADDRESS)"
              --verbosity 2
          ports:
            - name: http
              containerPort: 8545
              protocol: TCP
            - name: ws
              containerPort: 8546
              protocol: TCP
            - name: sync
              containerPort: 30303
              protocol: TCP
            - name: discovery
              containerPort: 30303
              protocol: UDP
          env:
            - name: NODE_NAME
              value: "dropps-test"
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
            - name: ETH_STATS_ADDRESS
              value: "ws-stats.execution.testnet.lukso.network"

            # SECRETS
            - name: ETH_STATS_SECRET
              valueFrom:
                secretKeyRef:
                  name: lukso
                  key: ETH_STATS_SECRET
                  optional: true
  #        securityContext:
  #          allowPrivilegeEscalation: false
  #          runAsNonRoot: true
#          resources:
#            requests:
#              cpu: 50m
#              memory: 8Gi
#            limits:
#              memory: 8Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: geth-conf
              mountPath: /configs
              readOnly: true
            - name: secrets
              mountPath: /var/run/secrets
              readOnly: true

        ## CONSENSUS:PRYSM (BEACON CHAIN)
        - name: beacon
          image: prysmaticlabs/prysm-beacon-chain:v4.0.5
          args:
            - --config-file=/configs/prysm.yaml
            - --verbosity=warn
          volumeMounts:
            - name: data
              mountPath: /data
            - name: prysm-conf
              mountPath: /configs
              readOnly: true
            - name: secrets
              mountPath: /var/run/secrets
              readOnly: true
      volumes:
        - name: geth-conf
          configMap:
            name: geth-conf
        - name: prysm-conf
          configMap:
            name: prysm-conf
        - name: secrets
          secret:
            secretName: lukso
            items:
              - key: JWT_SECRET
                path: JWT_SECRET
#      securityContext:
#        fsGroup: 1000
#        runAsUser: 1000
#        runAsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: lukso
#  labels:
#    app: lukso
#spec:
#  selector:
#    app: lukso
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
