grafanaHost: 'metrics.testnet.leequid.io'
grafanaStaticIPName: 'grafana-dev'
grafana:
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # selectorLabels: {}
    # subPath: ""
    # existingClaim:
    # extraPvcLabels: {}
